# NumPy

Numpy is included in the Pandas library, it can be installed in two ways:

```
 pip install numpy
 pip install pandas
```
**Use NumPy**

In [1]:
import numpy as np

**Array NumPy**

Array is the main use in Numpy.
There two types of array :
   1. One dimensional array (vector)
   2. Multidimensional array (matrix)

**Create a table from a List**

In [2]:
my_list = np.array([1,2,3,4,5,6,7,8,9,10])
my_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Create a table from an integration method**

*arange*

Returns evenly spaced values in a given interval.

In [4]:
my_list2 = np.arange(0,11)
my_list2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

*Zeros & Ones*

Generate arrays of zeros or ones

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

*eye*


In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

*linspace*

Returns evenly spaced numbers over a specified interval.

In [10]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [11]:
np.linspace(0,100,51)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

*Random*

*Rand*

Create an array of the given form and fill it with random samples from a uniform distribution on [0,1]

In [12]:
np.random.rand(2)

array([0.33873562, 0.83719563])

In [13]:
np.random.rand(5,5)

array([[0.52249404, 0.07030515, 0.99244413, 0.77793368, 0.43921741],
       [0.41285888, 0.95904536, 0.47212486, 0.55117157, 0.23821795],
       [0.32547189, 0.22852859, 0.99523107, 0.11928668, 0.6605855 ],
       [0.24988128, 0.16533342, 0.87540868, 0.63763197, 0.61972659],
       [0.64682684, 0.9337785 , 0.13513682, 0.93396749, 0.87724404]])

*Randn*

Returns a sample of the "standard normal" distribution. Unlike rand which is uniform

In [14]:
np.random.randn(2)

array([0.68344811, 2.39307479])

In [15]:
np.random.randn(5,5)

array([[-1.08327017,  0.12218085,  0.42065191,  1.29950078,  0.24180997],
       [-0.47590963,  0.39729626,  1.71785419,  0.89772253,  0.13285081],
       [-0.82555143,  0.69309938, -0.96471168, -1.66444709,  1.96239591],
       [ 0.09677664,  0.87292603, -0.6727332 , -0.73387836,  1.34982974],
       [ 1.87658367, -0.69938243, -0.49666924,  0.5904136 ,  2.04278601]])

*Randint*

Returns random integers from `low` (inclusive) to `high` (exclusive)

In [16]:
np.random.randint(1,100)

59

In [17]:
np.random.randint(1,100,10)

array([36, 24, 31, 90, 94, 61, 80, 42, 13, 57])

*Random Seed*

To fix (seed) the random number, we use `np.random.seed`

In [18]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])

**reshape**

Returns an array containing the same data with a new shape

In [19]:
arr = np.arange(25)

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

*max, min, argmax, argmin*

max, min return the max, min of an array

argmax, argmin return the index of the max, min of an array

In [21]:
ran_arr = np.random.randint(0,50,10)

In [22]:
ran_arr.max()

47

In [23]:
np.max(ran_arr)

47

In [24]:
ran_arr.min()

4

In [25]:
np.min(ran_arr)

4

In [26]:
ran_arr.argmax()

4

In [27]:
ran_arr.argmin()

8

Sum by Column

In [28]:
arr = np.arange(25).reshape(5,5)
np.sum(arr, axis=0)

array([50, 55, 60, 65, 70])

Sum by line

In [29]:
arr = np.arange(25).reshape(5,5)
np.sum(arr, axis=1)

array([ 10,  35,  60,  85, 110])

*Shape*

Return the dimension of an array

In [30]:
arr.shape

(5, 5)

*dtype*

Return the data type of the object in the array

In [31]:
arr.dtype

dtype('int32')