# NumPy

Numpy is included in the Pandas library, it can be installed in two ways:

```
 pip install numpy
 pip install pandas
```
**Use NumPy**

In [1]:
import numpy as np

**Array NumPy**
Array is the main use in Numpy.
There two types of array :
   1. One dimensional array (vector)
   2. Multidimensional array (matrix)

**Create a table from a List**

In [2]:
my_list = np.array([1,2,3,4,5,6,7,8,9,10])
my_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Create a table from an integration method**
*arange*
Returns evenly spaced values in a given interval.

In [4]:
my_list2 = np.arange(0,11)
my_list2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

*Zeros & Ones*
Generates arrays of zeros or ones

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

*linspace*
Returns evenly spaced numbers over a specified interval.

In [9]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [10]:
np.linspace(0,100,51)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

*Random*
*Rand*
Create an array of the given form and fill it with random samples from a uniform distribution on [0,1]

In [11]:
np.random.rand(2)

array([0.40907288, 0.95056872])

In [12]:
np.random.rand(5,5)

array([[0.59183823, 0.51220378, 0.68204452, 0.23432931, 0.29014905],
       [0.61387463, 0.62917035, 0.20701412, 0.36082063, 0.86046779],
       [0.96704765, 0.88357326, 0.03323868, 0.04154095, 0.56511678],
       [0.7677017 , 0.46009831, 0.28439794, 0.09752726, 0.30393683],
       [0.86940713, 0.45797683, 0.53721766, 0.52560532, 0.06420993]])

*Randn*
Returns a sample of the "standard normal" distribution. Unlike rand which is uniform

In [14]:
np.random.randn(2)

array([1.04170396, 0.14752045])

In [15]:
np.random.randn(5,5)

array([[-0.97524829,  0.91962071,  1.08569081, -0.92138457,  0.74909482],
       [-0.29169792, -1.65429018,  1.46522164,  0.08232895,  1.46704653],
       [ 0.89568751,  0.07478868, -0.5603055 ,  1.25783529,  1.16240424],
       [-0.39601512,  0.26852886,  1.07542603, -1.90455051,  0.93362544],
       [-0.18785823,  0.90469376, -0.59226321,  0.14617173,  0.40930764]])

*Randint*
Returns random integers from `low` (inclusive) to `high` (exclusive)

In [16]:
np.random.randint(1,100)

15

In [17]:
np.random.randint(1,100,10)

array([27, 25, 95,  9, 38, 18, 62, 39, 76,  5])

**reshape**
Returns an array containing the same data with a new shape

In [21]:
arr = np.arange(25)

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

*max, min, argmax, argmin*
max, min return the max, min of an array
argmax, argmin return the index of the max, min of an array

In [23]:
ran_arr = np.random.randint(0,50,10)

In [24]:
ran_arr.max()

46

In [26]:
np.max(ran_arr)

46

In [27]:
ran_arr.min()

8

In [28]:
np.min(ran_arr)

8

In [29]:
ran_arr.argmax()

4

In [30]:
ran_arr.argmin()

2

*Shape*
Return the dimension of an array

In [33]:
arr.shape

(25,)

*dtype*
Return the data type of the object in the array

In [35]:
arr.dtype

dtype('int32')