### Indexing & Selection

In [1]:
import numpy as np
arr = np.arange(0,11)

In [2]:
arr[8]

8

In [3]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[6:]

array([ 6,  7,  8,  9, 10])

### Broadcasting

In [6]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr = np.arange(0,11)

In [8]:
slice_array = arr[0:6]
slice_array

array([0, 1, 2, 3, 4, 5])

In [10]:
slice_array[:] = 99
slice_array

array([99, 99, 99, 99, 99, 99])

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

The changes also happen in our original array!
To avoid that, we should use a copy method :

In [12]:
arr = np.arange(0,11)
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_array = arr_copy[0:6]
slice_array[:] = 99
slice_array

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Indexing

In [18]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
arr_2d[1]

array([20, 25, 30])

In [20]:
arr_2d[0,:]

array([ 5, 10, 15])

[ 0 , : ] displays the entire first line

In [21]:
arr_2d[:,-1]

array([15, 30, 45])

[ : , -1 ] displays the entire last column

#### For more help :
<img src= 'https://s2.qwant.com/thumbr/0x380/e/f/c01bff98594466ebc0010d2898208f123a92d43849fb809db543c82f2038c9/Numpy1.jpg?u=https%3A%2F%2Fmedia.geeksforgeeks.org%2Fwp-content%2Fuploads%2FNumpy1.jpg&q=0&b=1&p=0&a=1' width=500/>

## Conditional selection

In [24]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [27]:
bool_arr = arr > 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
arr[arr%2==0]

array([ 0,  2,  4,  6,  8, 10])

In [29]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])